# Generated by Django 4.2.2 on 2023-06-08 11:20

import django.contrib.auth.models
from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('updated_by', models.IntegerField(blank=True, null=True, verbose_name='Updated by')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='User Name')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name')),
                ('full_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=80, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='Phone Number')),
                ('no_of_gyms', models.IntegerField(blank=True, choices=[(1, 'Single Gym'), (2, 'Chain Of Gyms'), (3, 'Large Chain Of Gyms')], null=True, verbose_name='No of Gyms')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='Email Verified')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='Phone Verified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='SuperUser')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['id'],
                'index_together': {('email', 'phone_number', 'updated_at')},
            },
            managers=[
                ('objects', user.models.ActiveUserManager()),
                ('all_objects', user.models.ActiveObjectsManager()),
                ('all_delete_objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
