# Generated by Django 4.2.2 on 2023-06-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_phone_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='no_of_gyms',
        ),
        migrations.AddField(
            model_name='user',
            name='no_of_anime_watched',
            field=models.IntegerField(blank=True, null=True, verbose_name='No of Animes watched'),
        ),
        migrations.CreateModel(
            name='TopAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('updated_by', models.IntegerField(blank=True, null=True, verbose_name='Updated by')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of Anime')),
                ('total_seasons', models.IntegerField(blank=True, null=True, verbose_name='Total Seasons')),
                ('total_likes', models.IntegerField(blank=True, null=True, verbose_name='Total Likes by Users')),
            ],
            options={
                'verbose_name': 'BaseModel',
                'verbose_name_plural': 'BaseModels',
                'abstract': False,
                'index_together': {('created_at', 'updated_at')},
            },
        ),
    ]
